## PHYSICAL CONSTRAINTS
# IO standards

set_property PULLTYPE PULLUP [get_ports sc_NORT1]
set_property PULLTYPE PULLUP [get_ports sc_clk_sm]

set_property IOSTANDARD LVDS_25 [get_ports ADC_*]
set_property IOSTANDARD LVCMOS25 [get_ports nCNV]
set_property IOSTANDARD LVCMOS25 [get_ports nCMOS]
set_property IOSTANDARD LVCMOS25 [get_ports {dbgOut[*]}]
set_property IOSTANDARD LVDS_25 [get_ports {T_p[*]}]
set_property IOSTANDARD LVDS_25 [get_ports {T_n[*]}]
set_property IOSTANDARD LVDS_25 [get_ports CLK_*]
set_property IOSTANDARD LVCMOS33 [get_ports npwr_reset]
set_property IOSTANDARD LVCMOS33 [get_ports SCL_275]
set_property IOSTANDARD LVCMOS33 [get_ports SDA_275]
set_property IOSTANDARD LVCMOS12 [get_ports sc_NORT1]
set_property IOSTANDARD LVCMOS12 [get_ports sc_NORT2]
set_property IOSTANDARD LVCMOS12 [get_ports sc_NORTQ]
set_property IOSTANDARD LVCMOS12 [get_ports sc_ck_read]
set_property IOSTANDARD LVCMOS12 [get_ports sc_clk_sm]
set_property IOSTANDARD LVCMOS12 [get_ports sc_errorb]
set_property IOSTANDARD LVCMOS12 [get_ports sc_holdext]
set_property IOSTANDARD LVCMOS12 [get_ports sc_outd_probe]
set_property IOSTANDARD LVCMOS12 [get_ports sc_reset_n]
set_property IOSTANDARD LVCMOS12 [get_ports sc_rstb_i2c]
set_property IOSTANDARD LVCMOS12 [get_ports sc_rstb_probe]
set_property IOSTANDARD LVCMOS12 [get_ports sc_rstb_sc]
set_property IOSTANDARD LVCMOS12 [get_ports sc_rstn_read]
set_property IOSTANDARD LVCMOS12 [get_ports sc_scl]
set_property IOSTANDARD LVCMOS12 [get_ports sc_sda]
set_property IOSTANDARD LVCMOS12 [get_ports sc_trigext]
set_property IOSTANDARD LVCMOS12 [get_ports sc_val_evt]

# Package pins
# Clock capable pins (MRCC / SRCC)
set_property PACKAGE_PIN V4 [get_ports CLK_100M_p]
set_property PACKAGE_PIN W4 [get_ports CLK_100M_n]

set_property PACKAGE_PIN AB21 [get_ports npwr_reset]

#RADIOROC
set_property PACKAGE_PIN T14 [get_ports sc_scl]
set_property PACKAGE_PIN V15 [get_ports sc_sda]
set_property PACKAGE_PIN T15 [get_ports sc_clk_sm]
set_property PACKAGE_PIN AA16 [get_ports sc_val_evt]
set_property PACKAGE_PIN AB13 [get_ports sc_errorb]
set_property PACKAGE_PIN W12 [get_ports sc_rstn_read]
set_property PACKAGE_PIN Y17 [get_ports sc_ck_read]
set_property PACKAGE_PIN Y16 [get_ports sc_reset_n]
set_property PACKAGE_PIN V13 [get_ports sc_rstb_sc]
set_property PACKAGE_PIN W16 [get_ports sc_rstb_probe]
set_property PACKAGE_PIN U15 [get_ports sc_rstb_i2c]
set_property PACKAGE_PIN AB11 [get_ports sc_outd_probe]
set_property PACKAGE_PIN AB12 [get_ports sc_holdext]
set_property PACKAGE_PIN AB10 [get_ports sc_trigext]
set_property PACKAGE_PIN Y12 [get_ports sc_NORT2]
set_property PACKAGE_PIN AA11 [get_ports sc_NORT1]
set_property PACKAGE_PIN V10 [get_ports sc_NORTQ]

#Triggers from radioroc
set_property PACKAGE_PIN E16 [get_ports {T_p[63]}]
set_property PACKAGE_PIN J19 [get_ports {T_p[62]}]
set_property PACKAGE_PIN D14 [get_ports {T_p[61]}]
set_property PACKAGE_PIN G15 [get_ports {T_p[60]}]
set_property PACKAGE_PIN E21 [get_ports {T_p[59]}]
set_property PACKAGE_PIN M13 [get_ports {T_p[58]}]
set_property PACKAGE_PIN F18 [get_ports {T_p[57]}]
set_property PACKAGE_PIN B15 [get_ports {T_p[56]}]
set_property PACKAGE_PIN A18 [get_ports {T_p[55]}]
set_property PACKAGE_PIN J15 [get_ports {T_p[54]}]
set_property PACKAGE_PIN B21 [get_ports {T_p[53]}]
set_property PACKAGE_PIN G21 [get_ports {T_p[52]}]
set_property PACKAGE_PIN E22 [get_ports {T_p[51]}]
set_property PACKAGE_PIN C22 [get_ports {T_p[50]}]
set_property PACKAGE_PIN B20 [get_ports {T_p[49]}]
set_property PACKAGE_PIN D20 [get_ports {T_p[48]}]
set_property PACKAGE_PIN J20 [get_ports {T_p[47]}]
set_property PACKAGE_PIN E19 [get_ports {T_p[46]}]
set_property PACKAGE_PIN B17 [get_ports {T_p[45]}]
set_property PACKAGE_PIN F19 [get_ports {T_p[44]}]
set_property PACKAGE_PIN A15 [get_ports {T_p[43]}]
set_property PACKAGE_PIN C18 [get_ports {T_p[42]}]
set_property PACKAGE_PIN H17 [get_ports {T_p[41]}]
set_property PACKAGE_PIN G17 [get_ports {T_p[40]}]
set_property PACKAGE_PIN C13 [get_ports {T_p[39]}]
set_property PACKAGE_PIN F16 [get_ports {T_p[38]}]
set_property PACKAGE_PIN F13 [get_ports {T_p[37]}]
set_property PACKAGE_PIN D17 [get_ports {T_p[36]}]
set_property PACKAGE_PIN C14 [get_ports {T_p[35]}]
set_property PACKAGE_PIN M6 [get_ports {T_p[34]}]
set_property PACKAGE_PIN K21 [get_ports {T_p[33]}]
set_property PACKAGE_PIN E13 [get_ports {T_p[32]}]
set_property PACKAGE_PIN J14 [get_ports {T_p[31]}]
set_property PACKAGE_PIN L5 [get_ports {T_p[30]}]
set_property PACKAGE_PIN L19 [get_ports {T_p[29]}]
set_property PACKAGE_PIN M18 [get_ports {T_p[28]}]
set_property PACKAGE_PIN K13 [get_ports {T_p[27]}]
set_property PACKAGE_PIN P6 [get_ports {T_p[26]}]
set_property PACKAGE_PIN N18 [get_ports {T_p[25]}]
set_property PACKAGE_PIN K6 [get_ports {T_p[24]}]
set_property PACKAGE_PIN M3 [get_ports {T_p[23]}]
set_property PACKAGE_PIN P5 [get_ports {T_p[22]}]
set_property PACKAGE_PIN J5 [get_ports {T_p[21]}]
set_property PACKAGE_PIN R3 [get_ports {T_p[20]}]
set_property PACKAGE_PIN F3 [get_ports {T_p[19]}]
set_property PACKAGE_PIN H4 [get_ports {T_p[18]}]
set_property PACKAGE_PIN E2 [get_ports {T_p[17]}]
set_property PACKAGE_PIN P2 [get_ports {T_p[16]}]
set_property PACKAGE_PIN L3 [get_ports {T_p[15]}]
set_property PACKAGE_PIN K2 [get_ports {T_p[14]}]
set_property PACKAGE_PIN H3 [get_ports {T_p[13]}]
set_property PACKAGE_PIN K1 [get_ports {T_p[12]}]
set_property PACKAGE_PIN M1 [get_ports {T_p[11]}]
set_property PACKAGE_PIN L16 [get_ports {T_p[10]}]
set_property PACKAGE_PIN N4 [get_ports {T_p[9]}]
set_property PACKAGE_PIN N22 [get_ports {T_p[8]}]
set_property PACKAGE_PIN C2 [get_ports {T_p[7]}]
set_property PACKAGE_PIN E1 [get_ports {T_p[6]}]
set_property PACKAGE_PIN G1 [get_ports {T_p[5]}]
set_property PACKAGE_PIN K18 [get_ports {T_p[4]}]
set_property PACKAGE_PIN K4 [get_ports {T_p[3]}]
set_property PACKAGE_PIN R1 [get_ports {T_p[2]}]
set_property PACKAGE_PIN B1 [get_ports {T_p[1]}]
set_property PACKAGE_PIN H2 [get_ports {T_p[0]}]

# ADC
set_property PACKAGE_PIN K17 [get_ports ADC_SCKHG_p]
set_property PACKAGE_PIN A13 [get_ports ADC_SCKLG_p]
set_property PACKAGE_PIN L14 [get_ports ADC_HG_p]
set_property PACKAGE_PIN H13 [get_ports ADC_LG_p]
set_property PACKAGE_PIN F15 [get_ports nCNV]
set_property PACKAGE_PIN J16 [get_ports nCMOS]

set_property PACKAGE_PIN N15 [get_ports SCL_275]
set_property PACKAGE_PIN AB22 [get_ports SDA_275]

set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN P19} [get_ports pulse]

set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN AB18} [get_ports extTrg]

set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN R17} [get_ports dacSDI]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN T18} [get_ports dacSCLK]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN T20} [get_ports dacCS]

set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN AA5} [get_ports readRq_p]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN AA1} [get_ports cs_p]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN AA8} [get_ports sclk_p]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN AB3} [get_ports mosi_p]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN W1} [get_ports miso_p]


set_property PACKAGE_PIN R4 [get_ports {dbgOut[7]}]
set_property PACKAGE_PIN T4 [get_ports {dbgOut[6]}]
set_property PACKAGE_PIN T5 [get_ports {dbgOut[5]}]
set_property PACKAGE_PIN U5 [get_ports {dbgOut[4]}]
set_property PACKAGE_PIN W6 [get_ports {dbgOut[3]}]
set_property PACKAGE_PIN W5 [get_ports {dbgOut[2]}]
set_property PACKAGE_PIN U6 [get_ports {dbgOut[1]}]
set_property PACKAGE_PIN V5 [get_ports {dbgOut[0]}]

set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]




create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 65536 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list pll1/inst/clk_out4]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 4 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {devInterfInst/state[0]} {devInterfInst/state[1]} {devInterfInst/state[2]} {devInterfInst/state[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 4 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {i2cRadModule/state[0]} {i2cRadModule/state[1]} {i2cRadModule/state[2]} {i2cRadModule/state[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {radInterfInst/radioFSMInst/dataOutBuff[0]} {radInterfInst/radioFSMInst/dataOutBuff[1]} {radInterfInst/radioFSMInst/dataOutBuff[2]} {radInterfInst/radioFSMInst/dataOutBuff[3]} {radInterfInst/radioFSMInst/dataOutBuff[4]} {radInterfInst/radioFSMInst/dataOutBuff[5]} {radInterfInst/radioFSMInst/dataOutBuff[6]} {radInterfInst/radioFSMInst/dataOutBuff[7]} {radInterfInst/radioFSMInst/dataOutBuff[8]} {radInterfInst/radioFSMInst/dataOutBuff[9]} {radInterfInst/radioFSMInst/dataOutBuff[10]} {radInterfInst/radioFSMInst/dataOutBuff[11]} {radInterfInst/radioFSMInst/dataOutBuff[12]} {radInterfInst/radioFSMInst/dataOutBuff[13]} {radInterfInst/radioFSMInst/dataOutBuff[14]} {radInterfInst/radioFSMInst/dataOutBuff[15]} {radInterfInst/radioFSMInst/dataOutBuff[16]} {radInterfInst/radioFSMInst/dataOutBuff[17]} {radInterfInst/radioFSMInst/dataOutBuff[18]} {radInterfInst/radioFSMInst/dataOutBuff[19]} {radInterfInst/radioFSMInst/dataOutBuff[20]} {radInterfInst/radioFSMInst/dataOutBuff[21]} {radInterfInst/radioFSMInst/dataOutBuff[22]} {radInterfInst/radioFSMInst/dataOutBuff[23]} {radInterfInst/radioFSMInst/dataOutBuff[24]} {radInterfInst/radioFSMInst/dataOutBuff[25]} {radInterfInst/radioFSMInst/dataOutBuff[26]} {radInterfInst/radioFSMInst/dataOutBuff[27]} {radInterfInst/radioFSMInst/dataOutBuff[28]} {radInterfInst/radioFSMInst/dataOutBuff[29]} {radInterfInst/radioFSMInst/dataOutBuff[30]} {radInterfInst/radioFSMInst/dataOutBuff[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 2 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {radInterfInst/state[0]} {radInterfInst/state[1]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 3 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {radInterfInst/radioFSMInst/state__0[0]} {radInterfInst/radioFSMInst/state__0[1]} {radInterfInst/radioFSMInst/state__0[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 3 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {radInterfInst/radioFSMInst/state[0]} {radInterfInst/radioFSMInst/state[1]} {radInterfInst/radioFSMInst/state[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 7 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {i2cAddrRad[0]} {i2cAddrRad[1]} {i2cAddrRad[2]} {i2cAddrRad[3]} {i2cAddrRad[4]} {i2cAddrRad[5]} {i2cAddrRad[6]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 8 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {i2cDataRdRad[0]} {i2cDataRdRad[1]} {i2cDataRdRad[2]} {i2cDataRdRad[3]} {i2cDataRdRad[4]} {i2cDataRdRad[5]} {i2cDataRdRad[6]} {i2cDataRdRad[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 8 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {i2cDataWrRad[0]} {i2cDataWrRad[1]} {i2cDataWrRad[2]} {i2cDataWrRad[3]} {i2cDataWrRad[4]} {i2cDataWrRad[5]} {i2cDataWrRad[6]} {i2cDataWrRad[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list i2cBusyRad]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list i2cEnaRad]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list i2cRwRad]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list i2cRadModule/scl_clk]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list i2cRadModule/sda_ena_n]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_100M]
