## PHYSICAL CONSTRAINTS
# IO standards

set_property PULLTYPE PULLUP [get_ports sc_clk_sm]

set_property INTERNAL_VREF 0.6 [get_iobanks 15]
set_property INTERNAL_VREF 0.6 [get_iobanks 16]
set_property INTERNAL_VREF 0.6 [get_iobanks 34]
set_property INTERNAL_VREF 0.6 [get_iobanks 35]

set_property IOSTANDARD LVDS_25 [get_ports ADC_*]
set_property IOSTANDARD LVCMOS25 [get_ports nCNV]
set_property IOSTANDARD LVCMOS25 [get_ports nCMOS]
set_property IOSTANDARD LVCMOS25 [get_ports {dbgOut[*]}]
set_property IOSTANDARD HSUL_12 [get_ports {T_2[*]}]
set_property IOSTANDARD HSUL_12 [get_ports {T_1[*]}]
set_property IOSTANDARD LVDS_25 [get_ports CLK_*]
set_property IOSTANDARD LVCMOS33 [get_ports npwr_reset]
set_property IOSTANDARD LVCMOS33 [get_ports SCL_275]
set_property IOSTANDARD LVCMOS33 [get_ports SDA_275]
set_property IOSTANDARD LVCMOS12 [get_ports sc_NORT1]
set_property IOSTANDARD LVCMOS12 [get_ports sc_NORT2]
set_property IOSTANDARD LVCMOS12 [get_ports sc_NORTQ]
set_property IOSTANDARD LVCMOS12 [get_ports sc_ck_read]
set_property IOSTANDARD LVCMOS12 [get_ports sc_clk_sm]
set_property IOSTANDARD LVCMOS12 [get_ports sc_errorb]
set_property IOSTANDARD LVCMOS12 [get_ports sc_holdext]
set_property IOSTANDARD LVCMOS12 [get_ports sc_outd_probe]
set_property IOSTANDARD LVCMOS12 [get_ports sc_reset_n]
set_property IOSTANDARD LVCMOS12 [get_ports sc_rstb_i2c]
set_property IOSTANDARD LVCMOS12 [get_ports sc_rstb_probe]
set_property IOSTANDARD LVCMOS12 [get_ports sc_rstb_sc]
set_property IOSTANDARD LVCMOS12 [get_ports sc_rstn_read]
set_property IOSTANDARD LVCMOS12 [get_ports sc_scl]
set_property IOSTANDARD LVCMOS12 [get_ports sc_sda]
set_property IOSTANDARD LVCMOS12 [get_ports sc_trigext]
set_property IOSTANDARD LVCMOS12 [get_ports sc_val_evt]

# Package pins
# Clock capable pins (MRCC / SRCC)
set_property PACKAGE_PIN V4 [get_ports CLK_100M_p]
set_property PACKAGE_PIN W4 [get_ports CLK_100M_n]

set_property PACKAGE_PIN AB21 [get_ports npwr_reset]

#RADIOROC
set_property PACKAGE_PIN T14 [get_ports sc_scl]
set_property PACKAGE_PIN V15 [get_ports sc_sda]
set_property PACKAGE_PIN T15 [get_ports sc_clk_sm]
set_property PACKAGE_PIN AA16 [get_ports sc_val_evt]
set_property PACKAGE_PIN AB13 [get_ports sc_errorb]
set_property PACKAGE_PIN W12 [get_ports sc_rstn_read]
set_property PACKAGE_PIN Y17 [get_ports sc_ck_read]
set_property PACKAGE_PIN Y16 [get_ports sc_reset_n]
set_property PACKAGE_PIN V13 [get_ports sc_rstb_sc]
set_property PACKAGE_PIN W16 [get_ports sc_rstb_probe]
set_property PACKAGE_PIN U15 [get_ports sc_rstb_i2c]
set_property PACKAGE_PIN AB11 [get_ports sc_outd_probe]
set_property PACKAGE_PIN AB12 [get_ports sc_holdext]
set_property PACKAGE_PIN AB10 [get_ports sc_trigext]
set_property PACKAGE_PIN Y12 [get_ports sc_NORT2]
set_property PACKAGE_PIN AA11 [get_ports sc_NORT1]
set_property PACKAGE_PIN V10 [get_ports sc_NORTQ]

# Triggers from radioroc
set_property PACKAGE_PIN E16 [get_ports {T_2[63]}]
set_property PACKAGE_PIN J19 [get_ports {T_2[62]}]
set_property PACKAGE_PIN D14 [get_ports {T_2[61]}]
set_property PACKAGE_PIN G15 [get_ports {T_2[60]}]
set_property PACKAGE_PIN E21 [get_ports {T_2[59]}]
set_property PACKAGE_PIN M13 [get_ports {T_2[58]}]
set_property PACKAGE_PIN F18 [get_ports {T_2[57]}]
set_property PACKAGE_PIN B15 [get_ports {T_2[56]}]
set_property PACKAGE_PIN A18 [get_ports {T_2[55]}]
set_property PACKAGE_PIN J15 [get_ports {T_2[54]}]
set_property PACKAGE_PIN B21 [get_ports {T_2[53]}]
set_property PACKAGE_PIN G21 [get_ports {T_2[52]}]
set_property PACKAGE_PIN E22 [get_ports {T_2[51]}]
set_property PACKAGE_PIN C22 [get_ports {T_2[50]}]
set_property PACKAGE_PIN B20 [get_ports {T_2[49]}]
set_property PACKAGE_PIN D20 [get_ports {T_2[48]}]
set_property PACKAGE_PIN J20 [get_ports {T_2[47]}]
set_property PACKAGE_PIN E19 [get_ports {T_2[46]}]
set_property PACKAGE_PIN B17 [get_ports {T_2[45]}]
set_property PACKAGE_PIN F19 [get_ports {T_2[44]}]
set_property PACKAGE_PIN A15 [get_ports {T_2[43]}]
set_property PACKAGE_PIN C18 [get_ports {T_2[42]}]
set_property PACKAGE_PIN H17 [get_ports {T_2[41]}]
set_property PACKAGE_PIN G17 [get_ports {T_2[40]}]
set_property PACKAGE_PIN C13 [get_ports {T_2[39]}]
set_property PACKAGE_PIN F16 [get_ports {T_2[38]}]
set_property PACKAGE_PIN F13 [get_ports {T_2[37]}]
set_property PACKAGE_PIN D17 [get_ports {T_2[36]}]
set_property PACKAGE_PIN C14 [get_ports {T_2[35]}]
set_property PACKAGE_PIN M6 [get_ports {T_2[34]}]
set_property PACKAGE_PIN K21 [get_ports {T_2[33]}]
set_property PACKAGE_PIN E13 [get_ports {T_2[32]}]
set_property PACKAGE_PIN J14 [get_ports {T_2[31]}]
set_property PACKAGE_PIN L5 [get_ports {T_2[30]}]
set_property PACKAGE_PIN L19 [get_ports {T_2[29]}]
set_property PACKAGE_PIN M18 [get_ports {T_2[28]}]
set_property PACKAGE_PIN K13 [get_ports {T_2[27]}]
set_property PACKAGE_PIN P6 [get_ports {T_2[26]}]
set_property PACKAGE_PIN N18 [get_ports {T_2[25]}]
set_property PACKAGE_PIN K6 [get_ports {T_2[24]}]
set_property PACKAGE_PIN M3 [get_ports {T_2[23]}]
set_property PACKAGE_PIN P5 [get_ports {T_2[22]}]
set_property PACKAGE_PIN J5 [get_ports {T_2[21]}]
set_property PACKAGE_PIN R3 [get_ports {T_2[20]}]
set_property PACKAGE_PIN F3 [get_ports {T_2[19]}]
set_property PACKAGE_PIN H4 [get_ports {T_2[18]}]
set_property PACKAGE_PIN E2 [get_ports {T_2[17]}]
set_property PACKAGE_PIN P2 [get_ports {T_2[16]}]
set_property PACKAGE_PIN L3 [get_ports {T_2[15]}]
set_property PACKAGE_PIN K2 [get_ports {T_2[14]}]
set_property PACKAGE_PIN H3 [get_ports {T_2[13]}]
set_property PACKAGE_PIN K1 [get_ports {T_2[12]}]
set_property PACKAGE_PIN M1 [get_ports {T_2[11]}]
set_property PACKAGE_PIN L16 [get_ports {T_2[10]}]
set_property PACKAGE_PIN N4 [get_ports {T_2[9]}]
set_property PACKAGE_PIN N22 [get_ports {T_2[8]}]
set_property PACKAGE_PIN C2 [get_ports {T_2[7]}]
set_property PACKAGE_PIN E1 [get_ports {T_2[6]}]
set_property PACKAGE_PIN G1 [get_ports {T_2[5]}]
set_property PACKAGE_PIN K18 [get_ports {T_2[4]}]
set_property PACKAGE_PIN K4 [get_ports {T_2[3]}]
set_property PACKAGE_PIN R1 [get_ports {T_2[2]}]
set_property PACKAGE_PIN B1 [get_ports {T_2[1]}]
set_property PACKAGE_PIN H2 [get_ports {T_2[0]}]

set_property PACKAGE_PIN D16 [get_ports {T_1[63]}]
set_property PACKAGE_PIN H19 [get_ports {T_1[62]}]
set_property PACKAGE_PIN D15 [get_ports {T_1[61]}]
set_property PACKAGE_PIN G16 [get_ports {T_1[60]}]
set_property PACKAGE_PIN D21 [get_ports {T_1[59]}]
set_property PACKAGE_PIN L13 [get_ports {T_1[58]}]
set_property PACKAGE_PIN E18 [get_ports {T_1[57]}]
set_property PACKAGE_PIN B16 [get_ports {T_1[56]}]
set_property PACKAGE_PIN A19 [get_ports {T_1[55]}]
set_property PACKAGE_PIN H15 [get_ports {T_1[54]}]
set_property PACKAGE_PIN A21 [get_ports {T_1[53]}]
set_property PACKAGE_PIN G22 [get_ports {T_1[52]}]
set_property PACKAGE_PIN D22 [get_ports {T_1[51]}]
set_property PACKAGE_PIN B22 [get_ports {T_1[50]}]
set_property PACKAGE_PIN A20 [get_ports {T_1[49]}]
set_property PACKAGE_PIN C20 [get_ports {T_1[48]}]
set_property PACKAGE_PIN J21 [get_ports {T_1[47]}]
set_property PACKAGE_PIN D19 [get_ports {T_1[46]}]
set_property PACKAGE_PIN B18 [get_ports {T_1[45]}]
set_property PACKAGE_PIN F20 [get_ports {T_1[44]}]
set_property PACKAGE_PIN A16 [get_ports {T_1[43]}]
set_property PACKAGE_PIN C19 [get_ports {T_1[42]}]
set_property PACKAGE_PIN H18 [get_ports {T_1[41]}]
set_property PACKAGE_PIN G18 [get_ports {T_1[40]}]
set_property PACKAGE_PIN B13 [get_ports {T_1[39]}]
set_property PACKAGE_PIN E17 [get_ports {T_1[38]}]
set_property PACKAGE_PIN F14 [get_ports {T_1[37]}]
set_property PACKAGE_PIN C17 [get_ports {T_1[36]}]
set_property PACKAGE_PIN C15 [get_ports {T_1[35]}]
set_property PACKAGE_PIN M5 [get_ports {T_1[34]}]
set_property PACKAGE_PIN K22 [get_ports {T_1[33]}]
set_property PACKAGE_PIN E14 [get_ports {T_1[32]}]
set_property PACKAGE_PIN H14 [get_ports {T_1[31]}]
set_property PACKAGE_PIN L4 [get_ports {T_1[30]}]
set_property PACKAGE_PIN L20 [get_ports {T_1[29]}]
set_property PACKAGE_PIN L18 [get_ports {T_1[28]}]
set_property PACKAGE_PIN K14 [get_ports {T_1[27]}]
set_property PACKAGE_PIN N5 [get_ports {T_1[26]}]
set_property PACKAGE_PIN N19 [get_ports {T_1[25]}]
set_property PACKAGE_PIN J6 [get_ports {T_1[24]}]
set_property PACKAGE_PIN M2 [get_ports {T_1[23]}]
set_property PACKAGE_PIN P4 [get_ports {T_1[22]}]
set_property PACKAGE_PIN H5 [get_ports {T_1[21]}]
set_property PACKAGE_PIN R2 [get_ports {T_1[20]}]
set_property PACKAGE_PIN E3 [get_ports {T_1[19]}]
set_property PACKAGE_PIN G4 [get_ports {T_1[18]}]
set_property PACKAGE_PIN D2 [get_ports {T_1[17]}]
set_property PACKAGE_PIN N2 [get_ports {T_1[16]}]
set_property PACKAGE_PIN K3 [get_ports {T_1[15]}]
set_property PACKAGE_PIN J2 [get_ports {T_1[14]}]
set_property PACKAGE_PIN G3 [get_ports {T_1[13]}]
set_property PACKAGE_PIN J1 [get_ports {T_1[12]}]
set_property PACKAGE_PIN L1 [get_ports {T_1[11]}]
set_property PACKAGE_PIN K16 [get_ports {T_1[10]}]
set_property PACKAGE_PIN N3 [get_ports {T_1[9]}]
set_property PACKAGE_PIN M22 [get_ports {T_1[8]}]
set_property PACKAGE_PIN B2 [get_ports {T_1[7]}]
set_property PACKAGE_PIN D1 [get_ports {T_1[6]}]
set_property PACKAGE_PIN F1 [get_ports {T_1[5]}]
set_property PACKAGE_PIN K19 [get_ports {T_1[4]}]
set_property PACKAGE_PIN J4 [get_ports {T_1[3]}]
set_property PACKAGE_PIN P1 [get_ports {T_1[2]}]
set_property PACKAGE_PIN A1 [get_ports {T_1[1]}]
set_property PACKAGE_PIN G2 [get_ports {T_1[0]}]

# ADC
set_property PACKAGE_PIN K17 [get_ports ADC_SCKHG_p]
set_property PACKAGE_PIN A13 [get_ports ADC_SCKLG_p]
set_property PACKAGE_PIN L14 [get_ports ADC_HG_p]
set_property PACKAGE_PIN H13 [get_ports ADC_LG_p]
set_property PACKAGE_PIN F15 [get_ports nCNV]
set_property PACKAGE_PIN J16 [get_ports nCMOS]

set_property PACKAGE_PIN N15 [get_ports SCL_275]
set_property PACKAGE_PIN AB22 [get_ports SDA_275]

set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN P19} [get_ports pulse]

set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN AB18} [get_ports extTrg]

set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN R17} [get_ports dacSDI]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN T18} [get_ports dacSCLK]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN T20} [get_ports dacCS]

set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN AA5} [get_ports readRq_p]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN AA1} [get_ports cs_p]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN AA8} [get_ports sclk_p]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN AB3} [get_ports mosi_p]
set_property -dict {IOSTANDARD LVDS_25 PACKAGE_PIN W1} [get_ports miso_p]


set_property PACKAGE_PIN R4 [get_ports {dbgOut[7]}]
set_property PACKAGE_PIN T4 [get_ports {dbgOut[6]}]
set_property PACKAGE_PIN T5 [get_ports {dbgOut[5]}]
set_property PACKAGE_PIN U5 [get_ports {dbgOut[4]}]
set_property PACKAGE_PIN W6 [get_ports {dbgOut[3]}]
set_property PACKAGE_PIN W5 [get_ports {dbgOut[2]}]
set_property PACKAGE_PIN U6 [get_ports {dbgOut[1]}]
set_property PACKAGE_PIN V5 [get_ports {dbgOut[0]}]

set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]
set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 65536 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list pll1/inst/clk_out5]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 1 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list trgSamplerInst/cntNSAftTrgEn]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list trgSamplerInst/cntNSAftTrgSet]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list trgSamplerInst/cntNSAftTrgSig]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list trgSamplerInst/cntTmrSet]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list trgSamplerInst/cntTmrSig]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list evtTrigger]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_200M]
