----------------------------------------------------------------------------------
-- PBR Cherenkov Telescope MPPC acquisition board
--
-- Module Name: adc (refactored)
-- Target Devices: Artix 7 xc7a200tfbg484-2
--
-- Refactor notes:
--   * Single clock domain (clk_200M only). clk_100M no longer needed; the parent
--     module port-map must be updated.
--   * adc_sck is generated by a toggle FF in the clk_200M domain (200 MHz / 2 =
--     100 MHz). No BUFGCE on a divided clock, no clock-as-data sampling.
--   * Deserializer, SCK rising-edge counter and FIFO write are all in clk_200M.
--     No CDC, no two-cycle wenFF/wenSync alignment, no async reset on the
--     deserializer.
--   * shift_en = en_adc_sck AND adc_sck_int : combinational, asserts exactly
--     once per generated SCK period, in the cycle of the rising edge.
--   * adc_sck_int is also gated by sck_cnt = 16 to guarantee exactly 16 SCK
--     rising edges (and 16 shifts) per channel - no spurious 17th edge when
--     leaving read_adc.
--   * cpt is signed and saturates at -1 in states where it is not reloaded, so
--     it can never wrap to 4095 by accident (latent bug in the original).
--   * fsmOut process uses default assignments + per-state overrides.
----------------------------------------------------------------------------------

library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use ieee.std_logic_misc.all;

library UNISIM;
use UNISIM.vcomponents.all;

library xpm;
use xpm.vcomponents.all;

library xil_defaultlib;

entity adc is
    port (
        rst               : in  std_logic;
        clk_200M          : in  std_logic;
        start             : in  std_logic;
        sdo_hg            : in  std_logic;
        sdo_lg            : in  std_logic;
        NORT1             : in  std_logic;
        NORT2             : in  std_logic;
        NORTQ             : in  std_logic;
        nb_acq            : in  std_logic_vector(7 downto 0);
        t                 : in  std_logic_vector(63 downto 0);
        sel_adc           : in  std_logic_vector(63 downto 0);
        rd_en             : in  std_logic;
        dout              : out std_logic_vector(7 downto 0);
        reset_n           : out std_logic;
        rstb_rd           : out std_logic;
        ck_read           : out std_logic;
        n_cnv             : out std_logic;
        adc_sck           : out std_logic;
        empty_acq         : out std_logic;
        end_multi_acq     : out std_logic;
        rd_data_count_acq : out std_logic_vector(16 downto 0);
        hold_ext          : out std_logic;
        trig_ext          : out std_logic;
        trig_out          : out std_logic;
        evtTrigger        : out std_logic;
        pulsing           : in  std_logic;
        pulse             : in  std_logic;
        extTrg            : in  std_logic;
        endAcq            : out std_logic;
        rdValid           : out std_logic
    );
end adc;

architecture Behavioral of adc is

    component fifo_acq
        port (
            clk           : in  std_logic;
            srst          : in  std_logic;
            din           : in  std_logic_vector(31 downto 0);
            wr_en         : in  std_logic;
            rd_en         : in  std_logic;
            dout          : out std_logic_vector(7 downto 0);
            full          : out std_logic;
            empty         : out std_logic;
            valid         : out std_logic;
            rd_data_count : out std_logic_vector(16 downto 0)
        );
    end component;

    type state_t is (init, idle, wait_hold, rst_cpt, wait_conv,
                     asrt_rd_high, asrt_rd_low, nxt, read_asic,
                     start_conv, end_conv, read_adc, end_read_adc,
                     write_fifo, finish);

    signal current_state, next_state : state_t;

    -- cpt: signed so we can saturate cleanly at -1 instead of wrapping
    signal cpt        : signed(12 downto 0);
    signal sck_cnt    : unsigned(4 downto 0);
    signal ch         : natural range 0 to 80;
    signal hold_delay : natural range 0 to 4095;
    signal conv_delay : natural range 0 to 2047;

    signal hit0, hit, en_acq      : std_logic;
    signal end_acq                : std_logic;
    signal wr_en                  : std_logic;

    signal sdo_hg_des, sdo_lg_des : std_logic_vector(15 downto 0);
    signal sdo_hglg               : std_logic_vector(31 downto 0);

    signal en_adc_sck             : std_logic;
    signal adc_sck_int            : std_logic;
    signal shift_en,
           firstEn                : std_logic;
    signal rstb_rd_s, rst_n       : std_logic;

    signal t0                     : std_logic;
    signal trigger, trgFF         : std_logic;
    signal trigger_sft, trgSftFF  : std_logic;
    signal trgEdge, trgSftEdge    : std_logic;
    signal holdext                : std_logic;

    signal NORT_FPGA              : std_logic;
    signal en_trigext             : std_logic;
    signal hd                     : std_logic_vector(11 downto 0);
    signal cd                     : std_logic_vector(10 downto 0);
    signal rdValidSig             : std_logic;
    signal locRst                 : std_logic;

begin

    evtTrigger <= trgEdge;
    trig_out   <= trigger_sft;
    endAcq     <= end_acq;
    rdValid    <= rdValidSig;
    NORT_FPGA  <= and_reduce(t);

--    locRstProc : process(clk_200M) 
--    begin
--        if rising_edge(clk_200M) then
            locRst <= rst;
--        end if;
--    end process;

    ----------------------------------------------------------------
    -- multi_acq instance (unchanged)
    ----------------------------------------------------------------
    ma : entity xil_defaultlib.multi_acq
        port map (
            rst           => locRst,
            clk_200M      => clk_200M,
            start         => start,
            end_acq       => end_acq,
            nb_acq        => nb_acq,
            en_acq        => en_acq,
            end_multi_acq => end_multi_acq,
            rst_n         => rst_n
        );

    ----------------------------------------------------------------
    -- adc_sck generation: toggle FF in clk_200M domain.
    --   While en_adc_sck = '1' and sck_cnt < 16, adc_sck_int toggles
    --   each clk_200M cycle, producing a 100 MHz square wave with
    --   exactly 16 rising edges per read_adc burst.
    --   Otherwise it is held at '0'.
    ----------------------------------------------------------------
    sckGen : process(clk_200M)
    begin
        if rising_edge(clk_200M) then
            if locRst = '1' or en_adc_sck = '0' or sck_cnt = 16 then
                adc_sck_int <= '0';
            else
                adc_sck_int <= not adc_sck_int;
            end if;
        end if;
    end process;

    -- shift_en is high for exactly one clk_200M cycle per generated
    -- SCK period, in the rising-edge cycle of adc_sck_int.
    shift_en <= en_adc_sck and adc_sck_int;

    adc_sck <= adc_sck_int;
    rstb_rd <= rstb_rd_s;

    ----------------------------------------------------------------
    -- Deserializer (16-bit shift register for HG and LG)
    --   Sync reset, sampled in clk_200M domain on shift_en.
    ----------------------------------------------------------------
    
    firstEnProc: process(clk_200M)
    begin
        if rising_edge(clk_200M) then
            if locRst = '1' then
                firstEn <= '0';
            else
                firstEn <= shift_en;
            end if;
        end if;
    end process;
    
    deserProc : process(clk_200M)
    begin
        if rising_edge(clk_200M) then
            if locRst = '1' or rstb_rd_s = '0' then
                sdo_hg_des <= (others => '0');
                sdo_lg_des <= (others => '0');
            elsif firstEn = '1' then
                sdo_hg_des <= sdo_hg_des(14 downto 0) & sdo_hg;
                sdo_lg_des <= sdo_lg_des(14 downto 0) & sdo_lg;
            end if;
        end if;
    end process;

    sdo_hglg <= sdo_hg_des & sdo_lg_des;

    ----------------------------------------------------------------
    -- SCK rising-edge counter (replaces adc_sck_vector / cpt_adc_sck)
    --   Reset to 0 on entry to end_conv (the cycle before read_adc)
    --   so the deserializer always starts a fresh 16-bit window.
    ----------------------------------------------------------------
    sckCntProc : process(clk_200M)
    begin
        if rising_edge(clk_200M) then
            if locRst = '1' or current_state = end_conv then
                sck_cnt <= (others => '0');
            elsif shift_en = '1' then
                sck_cnt <= sck_cnt + 1;
            end if;
        end if;
    end process;

    ----------------------------------------------------------------
    -- Acquisition FIFO (single domain: clk_200M only)
    ----------------------------------------------------------------
    ff : fifo_acq
        port map (
            srst          => locRst,
            clk           => clk_200M,
            din           => sdo_hglg,
            wr_en         => wr_en,
            rd_en         => rd_en,
            dout          => dout,
            full          => open,
            empty         => empty_acq,
            valid         => rdValidSig,
            rd_data_count => rd_data_count_acq
        );

    ----------------------------------------------------------------
    -- Trigger source mux + edge detection
    ----------------------------------------------------------------
    hit0 <= t(to_integer(unsigned(sel_adc(5 downto 0))));

    with sel_adc(31 downto 29) select
        t0 <= NORT1     when "000",
              NORT2     when "001",
              NORTQ     when "010",
              hit0      when "011",
              NORT_FPGA when "100",
              '0'       when others;

    hit <= not t0;

    trig_ext <= '0' when sel_adc(26) = '0' else (trigger or en_trigext);
    hold_ext <= sel_adc(27) and holdext;
    reset_n  <= sel_adc(6) when sel_adc(28) = '0' else rst_n;

    hd         <= sel_adc(54 downto 51) & sel_adc(39 downto 32);
    hold_delay <= to_integer(unsigned(hd));
    cd         <= sel_adc(63 downto 56) & "000";
    conv_delay <= to_integer(unsigned(cd));

    trigger     <= en_acq and hit;
    trigger_sft <= sel_adc(7);

    trgFFProc : process(clk_200M)
    begin
        if rising_edge(clk_200M) then
            if locRst = '1' then
                trgFF    <= '0';
                trgSftFF <= '0';
            else
                trgFF    <= trigger;
                trgSftFF <= trigger_sft;
            end if;
        end if;
    end process;

    trgEdge    <= trigger     and not trgFF;
    trgSftEdge <= trigger_sft and not trgSftFF;

    ----------------------------------------------------------------
    -- FSM: state register + delay counter + channel counter
    ----------------------------------------------------------------
    fsmSeq : process(clk_200M)
    begin
        if rising_edge(clk_200M) then
            if locRst = '1' then
                current_state <= init;
                cpt           <= (others => '0');
                ch            <= 0;
            else
                current_state <= next_state;

                -- cpt: load on entry to the corresponding state, otherwise
                -- decrement but saturate at -1 to avoid wrap-around.
                case current_state is
                    when idle =>
                        cpt <= to_signed(hold_delay, cpt'length);
                    when rst_cpt =>
                        cpt <= to_signed(conv_delay + 40, cpt'length);
                    when nxt =>
                        cpt <= to_signed(46, cpt'length);
                    when others =>
                        if cpt >= 0 then
                            cpt <= cpt - 1;
                        end if;
                end case;

                if current_state = idle then
                    ch <= 0;
                elsif current_state = end_conv then
                    ch <= ch + 1;
                end if;
            end if;
        end if;
    end process;

    ----------------------------------------------------------------
    -- FSM: next-state logic
    ----------------------------------------------------------------
    fsmComb : process(current_state, trgEdge, trgSftEdge, cpt, ch, sck_cnt)
    begin
        case current_state is
            when init =>
                next_state <= idle;
            when idle =>
                if trgEdge = '1' or trgSftEdge = '1' then
                    next_state <= wait_hold;
                else
                    next_state <= idle;
                end if;
            when wait_hold =>
                if cpt = 0 then
                    next_state <= rst_cpt;
                else
                    next_state <= wait_hold;
                end if;
            when rst_cpt =>
                next_state <= wait_conv;
            when wait_conv =>
                if cpt = 40 then
                    next_state <= asrt_rd_high;
                else
                    next_state <= wait_conv;
                end if;
            when asrt_rd_high =>
                if cpt = 20 then
                    next_state <= asrt_rd_low;
                else
                    next_state <= asrt_rd_high;
                end if;
            when asrt_rd_low =>
                if cpt = 0 then
                    next_state <= nxt;
                else
                    next_state <= asrt_rd_low;
                end if;
            when nxt =>
                if ch >= 66 then
                    next_state <= finish;
                elsif ch < 2 then
                    next_state <= start_conv;
                else
                    next_state <= read_asic;
                end if;
            when read_asic =>
                if cpt = 26 then
                    next_state <= start_conv;
                else
                    next_state <= read_asic;
                end if;
            when start_conv =>
                if cpt = 0 then
                    next_state <= end_conv;
                else
                    next_state <= start_conv;
                end if;
            when end_conv =>
                next_state <= read_adc;
            when read_adc =>
                if sck_cnt = 16 then
                    next_state <= end_read_adc;
                else
                    next_state <= read_adc;
                end if;
            when end_read_adc =>
                if ch < 3 then
                    next_state <= nxt;
                else
                    next_state <= write_fifo;
                end if;
            when write_fifo =>
                next_state <= nxt;
            when finish =>
                next_state <= idle;
            when others =>
                next_state <= idle;
        end case;
    end process;

    ----------------------------------------------------------------
    -- FSM: combinational outputs (defaults + per-state overrides)
    ----------------------------------------------------------------
    fsmOut : process(current_state)
    begin
        -- defaults: applied to every state, individual states override below
        rstb_rd_s  <= '1';
        holdext    <= '1';
        ck_read    <= '0';
        n_cnv      <= '0';
        en_adc_sck <= '0';
        wr_en      <= '0';
        end_acq    <= '0';
        en_trigext <= '0';

        case current_state is
            when init =>
                rstb_rd_s <= '0';
                holdext   <= '0';
            when idle =>
                holdext <= '0';
            when wait_hold =>
                rstb_rd_s  <= '0';
                holdext    <= '0';
                en_trigext <= '1';
            when rst_cpt =>
                en_trigext <= '1';
            when wait_conv =>
                en_trigext <= '1';
            when asrt_rd_high =>
                ck_read <= '1';
            when asrt_rd_low =>
                null;
            when nxt =>
                null;
            when read_asic =>
                ck_read <= '1';
            when start_conv =>
                n_cnv <= '1';
            when end_conv =>
                null;
            when read_adc =>
                en_adc_sck <= '1';
            when end_read_adc =>
                null;
            when write_fifo =>
                wr_en <= '1';
            when finish =>
                holdext <= '0';
                end_acq <= '1';
            when others =>
                holdext <= '0';
        end case;
    end process;

end Behavioral;